# -*- coding: utf-8 -*-

from imio.urban.dataimport.mapping import table

VALUES_MAPS = {

    'type_map': {
        'PUR': 'BuildLicence',
        'MPL': 'ParcelOutLicence',  # lotissement modifié
        'PLO': 'ParcelOutLicence',
        'DUR': 'Declaration',
        'CU2': 'UrbanCertificateTwo',
        'DEN': 'EnvClassThree',
        'PE2': 'EnvClassTwo',
        'PX2': 'EnvClassTwo',
        'PE1': 'EnvClassOne',
        'PX1': 'EnvClassOne',
        'PU1': 'UniqueLicence',
        'PU2': 'UniqueLicence',
    },

    'eventtype_id_map': table({
        'header'             : ['decision_event', 'college_report_event', 'deposit_event', 'complete_folder'],
        'BuildLicence'       : ['delivrance-du-permis-octroi-ou-refus', 'rapport-du-college', 'depot-de-la-demande','accuse-de-reception'],
        'ParcelOutLicence'   : ['delivrance-du-permis-octroi-ou-refus', 'rapport-du-college', 'depot-de-la-demande','accuse-de-reception'],
        'Declaration'        : ['deliberation-college', 'rapport-du-college', 'depot-de-la-demande',''],
        'UrbanCertificateOne': ['octroi-cu1', 'rapport-du-college', 'depot-de-la-demande', ''],
        'UrbanCertificateTwo': ['octroi-cu2', 'rapport-du-college', 'depot-de-la-demande', ''],
        'MiscDemand'         : ['deliberation-college', 'rapport-du-college', 'depot-de-la-demande',''],
        'EnvClassOne'        : ['decision', 'rapport-du-college', 'depot-de-la-demande', 'dossier-complet-recevable'],
        'EnvClassTwo'        : ['decision', 'rapport-du-college', 'depot-de-la-demande', 'dossier-complet-recevable'],
        'EnvClassThree'      : ['acceptation-de-la-demande', 'rapport-du-college', 'depot-de-la-demande',''],
        'UniqueLicence'      : ['delivrance-du-permis-octroi-ou-refus', 'rapport-du-college', 'depot-de-la-demande','accuse-de-reception'],
    }),

    'architects_id_map': {
        "1": "VAN DE SYPE Luc",
        "4": "PIRART R.",
        "5": "BEQUET Alain",
        "6": "MINDEN D.",
        "7": "DELOGNE A.",
        "8": "CAPIEAUX Frédéric",
        "9": "QUENON Benoît",
        "10": "FERRARD Michel",
        "11": "HUBERTY Annette",
        "12": "DELSAUT Jean-Marie",
        "13": "MAUCLET M.",
        "14": "SERRA DI MIGNI Mario",
        "15": "DE THIER Patrick",
        "16": "DEGHORAIN Auffray",
        "17": "de BUEGER Jean-Werner",
        "18": "DAEMS Anny",
        "19": "RIGUELLE Jacques",
        "20": "COLINET Bernard",
        "21": "HAMMOUD Hassan",
        "22": "VANDER STRICHT Christine",
        "23": "SOUMILLION Daniel",
        "24": "BOUHON Pascal",
        "25": "LEVÊQUE Claude",
        "26": "ROLAND Gaëtan",
        "27": "MILLECAMPS Pierre",
        "28": "TUMERELLE Joël",
        "29": "GHENNE Jean-Paul",
        "30": "JACQUEMIN Philippe",
        "31": "STIEVENART Jean-Pierre",
        "32": "RYELANDT Donatien",
        "33": "MATHIEUX Françoise",
        "34": "MERCIER Christophe",
        "35": "MUSCH Thierry",
        "36": "FAUCONNIER Frédéric",
        "37": "CONVENT Thierry",
        "38": "DE RO Paul",
        "39": "EVRARD Chantal",
        "40": "DELBROUCK Robert",
        "41": "BOSMAN Eric",
        "43": "COURTENS Patrice",
        "44": "CHEDID Tony",
        "45": "HAZART Vincent",
        "46": "VERHAMME Patrick",
        "47": "MEERSSEMAN Joël",
        "48": "DESTRA Girolamo",
        "49": "WINTERBEECK Walter",
        "50": "LALOUX Jean-Michel",
        "51": "SPURIO Cesare",
        "52": "SIMON Albert",
        "53": "LOWET Johan",
        "54": "VAN EETVELDE François",
        "55": "DUBOIS Bernard",
        "56": "PABIS Oldrzich",
        "57": "LAUWERYS Marylène",
        "58": "STRAGIER Nele",
        "59": "PETIT Paul",
        "60": "de CALLATAY Emmanuel",
        "61": "VANDEN HAUTE Hervé",
        "62": "DENAYER Philippe",
        "63": "COLLET Damien",
        "64": "FOUGÈRE Willy",
        "65": "BREDO Jean",
        "66": "CHOISEZ Pierre",
        "67": "D'HONDT Vincent",
        "68": "JOTTRAND Gilbert",
        "69": "RUBBERS Jean-Louis",
        "70": "DAUBE-RAHHAL Myrna",
        "71": "De Weerdt Willem",
        "72": "RION Gérard",
        "73": "VAN BESIEN Walter",
        "74": "BOULAND Eric",
        "75": "BENABDELOUAHED M.",
        "76": "TAS Patrick",
        "77": "DECKMYN Sébastien",
        "78": "NOIRHOMME Florence",
        "79": "BOONE Rik",
        "80": "THIBAUX Stéphane",
        "81": "NICODÈME Philippe",
        "83": "NIMMEGEERS Daniel",
        "84": "MARTELEUR Pascal",
        "86": "VANDEN DRIESSCHE Annette",
        "87": "LECAPITAINE Marc",
        "88": "DELGOFFE Eric",
        "89": "LEJEUNE Michel",
        "90": "DEVREUX Christine",
        "91": "PAQUET Freddy",
        "92": "de BONHOME Marc",
        "93": "COPPIN Marc",
        "94": "BERTOUILLE Philippe",
        "95": "VERREYT Roland",
        "97": "MAQUET Bernard",
        "98": "MATTOT René",
        "99": "BEGUIN Philippe",
        "100": "DE WAGTER Philippe",
        "101": "DALCQ Thierry",
        "106": "VOUSURE Annick",
        "107": "WALGRAVE Guido",
        "108": "DUEZ Thierry",
        "109": "SKIVENA Léon",
        "110": "ADANT Guy",
        "111": "VERBRUGGEN Laurent",
        "112": "RIGA Jean-Paul",
        "113": "VERDUSSEN Philippe",
        "114": "DEBIENNE Paul",
        "115": "VAN DE CASTEELE Daniel",
        "116": "MASSA André",
        "117": "LAHON Hugo",
        "118": "ARNOULD Denis",
        "119": "BAILYU Piet",
        "120": "DE MEYER Quentin",
        "121": "COUPEZ Joël",
        "123": "NÈVE Vincent",
        "124": "de SMEDT Nicolas",
        "125": "COLRUYT Piet",
        "126": "WINDEY Laurent",
        "128": "LINOS Costa",
        "129": "SIBENALER Charles",
        "130": "VAN BALLEGOOIJ Pascal",
        "131": "COGET Jean-Philippe",
        "132": "STINGLHAMBER Vincent",
        "133": "SINNESAEL Patrick",
        "134": "JACQUES Albert",
        "135": "BERLAIMONT Alain",
        "136": "PRIELS Olivier",
        "137": "AGLAVE Laurent",
        "138": "HERREGODS Martin",
        "139": "VAN DEN BRANDE Pierre-Marie",
        "140": "DUPONT André",
        "141": "LOUVRIER Didier",
        "142": "THOMAS Pierre",
        "143": "VERBRUGGHE Eric",
        "146": "WOLF Thierry",
        "147": "HUYGHE Jean-Michel",
        "148": "LEGROS Pierre",
        "149": "PEGORARO-POURBAIX",
        "150": "HOYOIS Henri",
        "151": "DELCERCK Ignace",
        "152": "MOENAERT Gérald",
        "153": "DI PIETRO Giansante",
        "154": "DI FONTE Giuliano",
        "155": "DEBAIZE John",
        "156": "JANSSENS Philippe",
        "157": "POTTIER Claude",
        "158": "WAGSCHAL Roger",
        "159": "CALLENS Cédric",
        "161": "BODART Jean",
        "162": "HOSTE Guy",
        "163": "VANDER MEEREN Yvan",
        "164": "RAHHAL Myrna",
        "165": "LIEVENS Jan",
        "166": "BRUNET Joël",
        "167": "WILLOCX Patrick",
        "168": "MORLION Jacques",
        "169": "DIRKX Anna",
        "170": "BRICHAUX Patrick",
        "171": "BRUYR Thibaut",
        "173": "VANDERLINDEN Philippe",
        "174": "VIERIN Xavier",
        "175": "JACQMOT Patrick",
        "176": "DEBEFVE Laurent",
        "177": "LAVEND'HOMME Gil",
        "179": "LECOYER Philippe",
        "180": "WELLENS Jean-Marc",
        "181": "BLONDIN Luc",
        "182": "DI MICHELE Pierino",
        "183": "",
        "184": "COOLS Pol",
        "185": "BEKAERT Herman",
        "186": "LANNOY Pierre Paul",
        "187": "MALDAGUE Jean-Marie",
        "188": "DE JONGHE Benoît",
        "189": "VERSTRAETE Yves",
        "191": "PICART Vincent",
        "192": "",
        "193": "FONTANA Jean-François",
        "194": "AHN Charles",
        "195": "PEETERS Kris",
        "197": "CATRIN Jean",
        "198": "STRYCKMAN Marc",
        "199": "DUPONT Charles",
        "201": "VAN CAMPENHOUT Eric",
        "202": "FRAITURE Georges",
        "203": "SCHYNS Isabelle",
        "204": "DOOMS Jean-Pierre",
        "205": "TIRCHER Philippe",
        "206": "BOVEROUX Jean",
        "207": "CALFF John",
        "209": "DANDOY Axelle",
        "210": "VAN DE WALLE Hugues",
        "211": "MEULEMAN Annie-Béatrice",
        "212": "CARBONNELLE Vincent",
        "213": "HORNY Olivier",
        "214": "VIENNE Guy",
        "216": "LENCHANT Michaël",
        "219": "DOZO Christophe",
        "220": "EECKHOUDT Jean-Luc",
        "221": "SCHUERMANS Jean-Paul",
        "222": "POURTOIS Erica",
        "223": "VIRGO Vincent",
        "224": "TAELMAN Wouter",
        "225": "MOUSSET Carmen",
        "226": "PRIGNOT Isabelle",
        "227": "BOURGEOIS Sébastien",
        "228": "MAES Daniel",
        "229": "WAUTIER Solange",
        "230": "BORGERS Alain",
        "231": "HENNE Fabien",
        "232": "M. LOMBAL & J. DU FOUR",
        "233": "SIMAL Jean-Luc",
        "235": "VAN HOVE Frédéric",
        "236": "CUVELIER Damien",
        "237": "RUMMEL Eric",
        "238": "MOMMENS Marc",
        "239": "KUNOKA Fabrice",
        "240": "HECQ Bernard",
        "242": "WATILLON Luc",
        "244": "VALVEKENS Christophe",
        "245": "WINDERICKX Bernard",
        "246": "MONNIER Gaëtan",
        "247": "GEORGES Michel",
        "248": "BERNARD Etienne",
        "249": "",
        "250": "VERDONCK Pierre",
        "251": "DE CLERCQ Eric",
        "252": "VANDENBERGHE Céline",
        "253": "TRIANTAFYLLOU Jean",
        "254": "MAILLARD Louis",
        "255": "BRAIBANT Xavier",
        "256": "RICHARTZHAGEN Jacques",
        "257": "SOYEUR Catherine",
        "258": "MOURIALMÉ Pierre",
        "259": "CNOCKAERT Nancy",
        "260": "VAN HAEREN Jacques",
        "261": "PLUMAT Michel",
        "263": "BICHARA Christophe",
        "264": "HENRY Ernest",
        "265": "THIROT Alain",
        "266": "SURLERAUX Jean-Pierre",
        "267": "CAUWE Damien",
        "268": "NOVIS Danielle",
        "269": "ROMBOUX Nathalie",
        "270": "TIMMERMANS Marc",
        "271": "DERNELLE Jonathan",
        "272": "VAN ESPEN Renaud",
        "273": "DEMAIN Bernard",
        "274": "INDENGE Guy",
        "275": "HOLEMANS Philippe",
        "276": "VAN COPPENOLLE Luc",
        "278": "MAES Nathalie",
        "279": "DISNEUR Patrick",
        "280": "ZOUAOUI Abderrezak",
        "281": "MARIETTOS Michaël",
        "282": "UYLENBROECK Yvette",
        "283": "ONSSELS Hervé",
        "284": "ARNOLD Sophie",
        "285": "VERHAEGEN Hugues",
        "286": "DELATTE Matthieu",
        "287": "GEEROMS Wim",
        "288": "VANDENDEURPEL Michel",
        "289": "Vincent JACOBS Fabian RAHIER et",
        "290": "DESCHOENMAEKER Frans",
        "291": "POPOV Lubomir",
        "292": "BIEMBONGO Ikamba",
        "293": "ARCQ Michèle",
        "294": "DEVILLÉ Laurent",
        "295": "FRÉCOURT Jean-Marie",
        "296": "BOSSCHEM Jan",
        "297": "DOSSIN Bénédicte",
        "298": "PARISI Gaëtan",
        "299": "VERBEKE Steven",
        "300": "DETROGH Georges",
        "301": "JANSSENS Philippe",
        "302": "VANDEN BRANDE Xavier",
        "303": "CHARLIER Didier",
        "304": "VAN NIEUWENHOVE JP",
        "305": "COURTOIS Jean-Benoit",
        "306": "CAUDRON Laurence",
        "307": "LEMERET Patrice",
        "308": "BRANCART Valérie",
        "309": "BRABANTS Andries",
        "310": "GOISSE Henri",
        "311": "VERBEECK Jacques",
        "312": "GUERRIAT Adeline",
        "313": "SEVRIN Etienne",
        "316": "WILLEAUME Luc",
        "317": "DE VIJLDER Patrick",
        "318": "DENAYER Yannick",
        "319": "MEURS Jean-Philippe",
        "320": "BASTIN Xavier",
        "321": "BUYLE Yannick",
        "322": "DISPAUX Frédéric",
        "323": "MICIC Gordana",
        "324": "CORNEMILLOT Laurent",
        "325": "LEGRAND Natacha",
        "326": "COCKENPOT Olivier",
        "327": "JANSSENS de VAREBEKE Géry",
        "328": "BAYART Catherine",
        "329": "BETS Grégory",
        "330": "DE DEURWAERDER Olivier",
        "331": "TOMBEUX Marc",
        "332": "VERLEYEN Etienne",
        "333": "VERLIEFDEN Michel",
        "334": "DEFOIN Marc",
        "335": "",
        "336": "DENRUYTER Pascal",
        "337": "DEKONINCK Maarten",
        "338": "DEBAENE Tom",
        "339": "LIPSZYC Catherine",
        "341": "ALEGRIA Federico",
        "342": "FALLON Nicolas",
        "343": "MACHIELS Véronique",
        "344": "NOACH Jacques",
        "345": "RIFFLART Ronald",
        "346": "THONNARD Marc",
        "348": "",
        "349": "GELDOF & MENTEN",
        "350": "BAILLY Emmanuel",
        "351": "DEGEZELLE Adélaïde",
        "352": "DUMBUYA Thierno",
        "353": "BRONCKART Alain",
        "354": "DE MOL Staf",
        "355": "JANSSEN Christophe",
        "356": "AUDRIT Jérôme",
        "357": "",
        "358": "POTTIER Claude",
        "359": "DE BEL Erik",
        "360": "VAN LAETHEM Erik",
        "361": "Leclercq",
        "362": "DECROIX Caroline",
        "363": "CORNÉLIS Vanessa",
        "364": "SYMENS Yves",
        "365": "BOSSCHEM Jan",
        "366": "DAELEMAN Laurent",
        "367": "COPPENS Stéphan",
        "368": "BOLLE Michael",
        "369": "BADIALI Sandro",
        "370": "BRUYÈRE Paul",
        "371": "MORISSENS Sophie",
        "372": "HANDRIEU Frédéric",
        "373": "CLERBOIS Gérard",
        "374": "FOSTIER Michel",
        "376": "AMIRI LAMRASKI Madjid",
        "378": "& Etienne GODIMUS Frank ALLAND",
        "379": "de VIRON Philibert",
        "380": "THAYS Frédérique",
        "381": "KASTALDI Jasmine",
        "382": "DEHASPE Yves",
        "383": "PÉTRÉ Christine",
        "384": "VAN HERREWEGE Philippe",
        "385": "ROBERT Alain",
        "386": "MOTTE Arnaud",
        "387": "BERSIPONT Stéphan",
        "388": "MOULIN Luc",
        "389": "CORNELISSENS Daniel",
        "390": "DULAIT Daphné",
        "391": "GOSSE Georges",
        "392": "VESELA Cestmira",
        "393": "GREVISSE Marylène",
        "394": "BRUYÈRE Étienne",
        "395": "VANEBERG Jean-Pierre",
        "396": "KROPEK Josip",
        "397": "RAPPEZ Nicolas",
        "398": "NAJEM Mohamed",
        "399": "VAN SOOM Peter",
        "400": "ANDRE Carien",
        "401": "DEKETELAERE Vincent",
        "402": "DUCHESNE Marc",
        "403": "TILIAKOS Nicolas",
        "404": "F. VAN CAUWENBERGE et J. LECLERCQ",
        "405": "SWAELENS Maurice",
        "406": "AERIKOS Stavros",
        "407": "JOSSART François",
        "408": "DEVOS Frédéric",
        "409": "MAES Michel",
        "410": "ALEXIS Jacques",
        "415": "LOMBART David",
        "416": "STREHLER René",
        "418": "JACQMIN Nicolas",
        "419": "THILS Laurence",
        "420": "LEMAN Geneviève",
        "422": "GIELEN Nicolas",
        "423": "MEGANCK Jacques",
        "424": "VELLA Salvatore",
        "425": "KAISER Gérard",
        "426": "BONDROIT Jean",
        "427": "PAINDAVEINE Pol",
        "430": "KINTS Hélène",
        "432": "",
        "433": "LELEUX Vincent",
        "434": "",
        "435": "HUWAERT Frédéric",
        "436": "MINCKE Stéphane",
        "437": "",
        "439": "HONTOIR Jan",
        "440": "PAUWELS Hugo",
        "441": "LEGROS Gérald",
        "442": "BEYL Paul",
        "443": "DELLICOUR Gregory",
        "444": "DEBROUX Jean-Luc",
        "445": "de LE HOYE Yves",
        "446": "WASCHALL Roger",
        "447": "CESTMIRA Vesela",
        "448": "JOURDAN Patrick",
        "449": "KISIELEWICZ Martin",
        "450": "MEUNIER Valérie",
        "451": "HENNEAU Olivier",
        "452": "DE CONINCK Bieke",
        "453": "de HEMPTINNE Arnaud",
        "454": "GRAILET Paul",
        "455": "HANTSON Audry",
        "456": "",
        "457": "PODEVIJN Julie",
        "458": "ADDARIO Pina",
        "459": "",
        "460": "HOUX Sophie",
        "461": "LEQUEUX Catherine",
        "462": "GRULOOS Pierre",
        "463": "BAYET Angéline",
        "464": "LEEMANS Christophe",
        "465": "DUFRASNE Philippe",
        "466": "LONCKE Thierry",
        "467": "",
        "468": "HERNALSTEEN Tom",
        "469": "BORREMANS Jean-Pol",
        "470": "RADERMACHER Olivier",
        "471": "LIZIN Bruno",
        "472": "HOSDIN Jean-François",
        "473": "BELDARS Emmanuel",
        "474": "HUART Jean-Luc",
        "475": "COURTENS Patrice",
        "476": "COLLARD Christian",
        "477": "FERIER Dimitri",
        "478": "FALMAGNE",
        "479": "JOURQUIN Mathieu",
        "480": "GILLOT Pierre",
        "481": "DANNAU Didier",
        "482": "DEWANDELEER Jean-François",
        "483": "DEBATTY Bernard",
        "484": "ZURECK Céline",
        "485": "CEBBAR Ismet",
        "487": "",
        "488": "ABRAHAM Pierre",
        "489": "DEMEULENAERE Thierry",
        "490": "KREMER Jean-François",
        "491": "DEBERGH Igor",
        "492": "KERVYN Stéphane",
        "493": "MOREIRA Kassandra",
        "494": "SCHMIT Sébastien",
        "495": "LIBERT Bernard",
        "496": "ERKENS Christophe",
        "497": "BALCAEN Luk",
        "498": "JAPSENNE Philippe",
        "499": "DURBECQ Michaël",
        "500": "DESMET Serge",
        "501": "DELSINE Christian",
        "502": "WISSAM Salim",
        "503": "CORIJN Jan",
        "504": "ROBA Gilles",
        "505": "VAN DER HEYDEN Xavier",
        "506": "RICCIARDONE Agostino",
        "507": "MÉLOTTE Robert",
        "508": "NAVEZ Jean-Pierre",
        "509": "HECK Marc",
        "510": "RENQUIN Jean-Marc",
        "511": "PRZYBYLSKI Frédéric",
        "512": "NISOLLE Stéphane",
        "513": "VERHELST Christiaan",
        "514": "STIENNON",
        "515": "SLOT Cathy",
        "516": "LAASSAL Adil",
        "517": "VAN VYVE Frédéric",
        "518": "FIEVEZ Jacques",
        "519": "WELLENS Michel",
        "520": "VANDEN NOORTGAETE Marjorie",
        "521": "DEBLANDRE Jean-Philippe",
        "522": "GENON Pierre",
        "523": "CATRY Danny",
        "524": "DAPRA Sandro",
        "525": "NEUSY Michael",
        "526": "ALBERT Alexandre",
        "527": "KREMER Jean-François",
        "528": "CHARPENTIER Carine",
        "529": "BRICHAUX Thierry",
        "530": "VAN WAUWE Sofie",
        "531": "",
        "532": "VERAART Martin",
        "533": "RASCHELLA Lorenzo",
        "536": "MAUROY F.",
        "537": "WYDEMANS Laurent",
        "538": "",
        "539": "MARTIN Lionel",
        "540": "MARCHAL Etienne",
        "541": "KACZMAREK Baptiste",
        "542": "GHARABAGHI Massood",
        "543": "SECHEHAYE Christophe",
        "544": "STASSEN Yves",
        "545": "VAN de SYPE Ann",
        "547": "FIEUW Cristof",
        "548": "BREYNE Toon",
        "549": "DE GROOTE Koen",
        "550": "",
        "551": "DE NEVE Geert",
        "552": "TSIMOPOULOS Dimitri",
        "553": "LIEFOOGHE Valérie",
        "554": "POLIART Edmond",
        "555": "Lebrun Sébastien",
        "556": "MONSEU Pierre",
        "558": "",
        "559": "Loir David",
        "560": "Mouligneau Pierre-Philippe",
        "561": "JANSSEN Serge",
        "562": "GOURDIN Julien",
        "563": "Mellouki Anes",
        "564": "FOULON Philippe",
        "565": "DE BUSSCHERE Dominique",
        "566": "VANDERHAEGEN Tanguy",
        "567": "",
        "568": "STERCKX Johan",
        "570": "VAN CALOEN François",
        "571": "DEMEYER Jean-Philippe",
        "572": "ALEXANDRE Raphaël",
        "574": "Madame Cécile FERAUGE Philippe MALHOMME et",
        "575": "BREYNE Toon",
        "576": "EL ASLI Ali",
        "577": "TERCELIN de JOIGNY de PAMELE Amaury",
        "578": "Guy Mathieu",
        "579": "De Windt Yves",
        "580": "COLLIN Christian",
        "581": "GILLE Marie",
        "583": "BAYET Christian",
        "584,": "Vincent DEHON",
        "585": "MONACHINO David",
        "586": "FLAMME Alexia",
        "587": "",
        "588": "MICHIELS Laurent",
        "589": "GRULOOS Pierre",
        "590": "DE FOUR Jan",
        "591": "DEWITTE Sarah",
        "592": "LAMY Thierry",
        "593": "RAYMAKERS & MELIKA",
        "594": "GIANNAROS Stavros",
        "595": "de PUYDT Vincent",
        "596": "NOEL Didier",
        "597": "BAUWENS Hugo",
        "598": "PLETSCHET Sylvie",
        "599": "VAN de VELDE Laurent",
        "600": "PETENO Jérôme",
        "601": "VAN PASSEL Laurent",
        "602": "VAN DAMME Bernard",
        "603": "",
        "604": "JAHN Olivier",
        "605": "LALOUX Benoît",
        "606": "MOREAU Grégory",
        "607": "LIBERT Serge",
        "608": "DE SAUVAGE Gael",
        "609": "LOPEZ AGUADO Mariano",
        "610": "LELEUX Vincent",
        "611": "FONTANAZZA Signorino",
        "612": "D'ALAYER DE COSTEMORE D'ARC Martin",
        "613": "AMIRI LAMRASKI Madjid",
        "614": "Fontana Cécile",
        "615": "MALDAGUE Jean-Marie",
        "616": "ROBERT Alain",
        "617": "WILPUTTE Mathieu",
        "620": "GOBLET Christian",
        "621": "SALIM Wissam",
        "622": "MAGOTTEAUX Pierre",
        "623": "BORKOWSKI Nadine",
        "624": "DERAEDT Bruno",
        "625": "NERINCKX Jean-Marie",
        "626": "de BONHOMME Frédéric",
        "627": "STAQUET Vincent",
        "628": "GAILLIEZ Robin",
        "629": "COSTER Denis",
        "630": "PATERNOSTER Julien",
        "631": "CLARES Abel",
        "632": "VERRALEWYCK Philippe",
        "634": "LECLEF Adelin",
        "635": "",
        "636": "VANTONGELEN Jean-Pierre",
        "637": "van der HEYDEN Xavier",
        "638": "",
        "639": "VERJUS Gengoux",
        "641": "LAMBERT Gilles",
        "642": "DUPONT Vincent",
        "643": "HOLLEVOET Frank",
        "644": "MELLOUKI Anes",
        "645": "NUTELET Thibaut",
        "646": "GENDARME Jerry",
        "647": "DUMONT Henri",
        "648": "",
        "649": "GRANDMAISON Emmanuel",
        "650": "THIEFFRY Marie-Dominique",
        "651": "VAN DAM Laurence",
        "652": "BRONDEL Jean-Philippe",
        "653": "STOCKMAN Jean-Philippe",
        "654": "ANTHOINE Philippe",
        "655": "VAN HAEREN Cédric",
        "656": "LINOS Costa",
        "657": "",
        "658": "VASTEELS Laurent",
        "659": "",
        "661": "AUTEM David",
        "662": "HENRY Philippe",
        "663": "DEBLIRE Philippe",
        "664": "VIATOUR Christian",
        "665": "DEPREZ André",
        "666": "HIRSCH Georges",
        "667": "LORIAUX Philippe",
        "668": "GRAINDORGE Jérôme",
        "669": "VERMEREN Philippe",
        "670": "GUSTIN Jean-François",
        "671": "",
        "672": "GODEAU Marc",
        "674": "BURNY Joël",
        "676": "SALAMONE Stefano",
        "677": "VANDENBLOCK Eric",
        "678": "FRANCOIS Grégory",
        "679": "LAUWERYS Maryline",
        "680": "de RIJCK Luckas",
        "681": "BORTNOWSKI Christine",
        "682": "DANDOIS Sophie-Charlotte",
        "683": "BORSEN Stéphane",
        "684": "LEMMENS Benoît",
        "685": "PARUBAJ Michel",
        "686": "ANDRE Michel",
        "688": "HUYLENBROECK Yvette",
        "689": "VLIEBERGH François",
        "690": "AERIKOU Stavros",
        "691": "DEPRÉAY Joëlle",
        "692": "COLPAERT Nicolas",
        "693": "THISSEN Martial",
        "694": "LEURIDENT François",
        "695": "BAUMANN Jacques",
        "697": "BOURGUIGNON Guy",
        "698": "LEBLANC Jean-David",
        "699": "GERMAIN Stéphanie",
        "700": "GENOT Philippe",
        "701": "HERTOGHE Cédric",
        "702": "& VANDEN EYNDE COSTER",
        "704": "PHILIPPART Bruno",
        "705": "COUILLIEN Christophe",
        "706": "QUERTAINMONT Frdéric",
        "707": "LECLERCQ Maïté",
        "708": "CIPOLAT Francesco",
    },

    'solicitOpinionDictionary': {
               '1' :        "service-technique-provincial", #Avis Service technique provincial
               '2' :        "direction-des-cours-deau", #Avis Dir Cours d'eau
               '3' :        "pi", #Avis Zone de secours
               '4' :        "ores", #Avis ORES
               '5' :        "cibe", #Avis Vivaqua
               '6' :        "agriculture", #Avis Dir Développement rural
               '7' :        "dnf", #Avis Département Nature et Forêts
               '8' :        "forces-armees", #Avis Forces armées
               '9' :        "spw-dgo1", #Avis Dir Routes BW
               '10':        "swde", #Avis SWDE/IECBW
               '11':        "belgacom", #Avis PROXIMUS
               '12':        "infrabel", #Avis TEC
               '13':        "ibw", #Avis IBW
               '14':        "voo", #Avis VOO
               '15':        "bec", #Avis Service technique communal
               '16':        "ccatm", #Avis CCATM
               '17':        "owd", #Avis OWD
            },

    'zoneDictionary': {
           "zone d'habitat à caractère rural"                                      : 'zhcr'                                         ,
           "zone agricole"                                                         : 'za'                                           ,
           "zone agricole d'intérêt paysager"                                      : 'zone-agricole-dinteret-paysager'              ,
           "zone d'activité économique industrielle"                               : 'zaei'                                         ,
           "zone d'activité économique industrielle (Wauthier-Braine)"             : 'zaei'                                         ,
           "zone d'activité économique mixte"                                      : 'zaem'                                         ,
           "zone d'aménagement communal concerté"                                  : 'zone-damenagement-communal-concerte'          ,
           "zone d'aménagement différé"                                            : 'zone-damenagement-differe'                    ,
           "zone d'espaces verts"                                                  : 'zev'                                          ,
           "zone d'espaces verts d'intérêt paysager"                               : 'zone-despaces-verts-dinteret-paysager'        ,
           "zone d'extraction"                                                     : 'ze'                                           ,
           "zone d'extraction sur fond de zone agricole"                           : 'zone-dextraction-sur-fond-de-zone-agricole'   ,
           "zone d'habitat"                                                        : 'zh'                                           ,
           "zone de loisirs"                                                       : 'zl'                                           ,
           "zone de parc"                                                          : 'zp'                                           ,
           "zone de parc d'intérêt paysager"                                       : 'zone-de-parc-dinteret-paysager'               ,
           "zone de services publics et d'équipements communautaires"              : 'zspec'                                        ,
           "zone forestière"                                                       : 'zf'                                           ,
           "zone forestière d'intérêt paysager"                                    : 'zone-forestiere-dinteret-paysager'            ,
           "zone non affectée"                                                     : 'zone-non-affectee'                            ,
    },

    'default_date_decision': '09/09/2099',
}